#load "Microsoft.CSharp.csx" 
#load "NETStandard.Library.csx" 
#load "System.ComponentModel.TypeConverter.csx" 
#load "System.Runtime.Serialization.Formatters.csx" 
#load "System.Runtime.Serialization.Primitives.csx" 
#load "System.Xml.XmlDocument.csx" 
#r "../../../packages/Newtonsoft.Json/lib/portable-net40+sl5+win8+wp8+wpa81/Newtonsoft.Json.dll" 