#load "Akka.csx" 
#load "FsPickler.csx" 
#load "FSPowerPack.Core.Community.csx" 
#load "FSPowerPack.Linq.Community.csx" 
#load "System.ValueTuple.csx" 
#r "../../../packages/Akka.FSharp/lib/net45/Akka.FSharp.dll" 