#load @"System.Collections.fsx" 
#load @"System.Reflection.fsx" 
#load @"System.Resources.ResourceManager.fsx" 
#load @"System.Runtime.fsx" 
#load @"System.Runtime.Serialization.Primitives.fsx" 
#r "../../../packages/System.Runtime.Serialization.Formatters/lib/netstandard1.4/System.Runtime.Serialization.Formatters.dll" 