#load @"System.Resources.ResourceManager.fsx" 
#load @"System.Runtime.fsx" 
#r "System.Runtime.Serialization" 
#r "System.Runtime.Serialization" 
#r "../../../packages/System.Runtime.Serialization.Primitives/lib/netstandard1.3/System.Runtime.Serialization.Primitives.dll" 