#load "System.Globalization.csx" 
#load "System.Resources.ResourceManager.csx" 
#load "System.Runtime.csx" 
#load "System.Runtime.Extensions.csx" 
#r "System.Numerics" 
#r "../../../packages/System.Runtime.Numerics/lib/netstandard1.3/System.Runtime.Numerics.dll" 