#load "System.Diagnostics.Debug.csx" 
#load "System.Diagnostics.Tracing.csx" 
#load "System.Resources.ResourceManager.csx" 
#load "System.Runtime.csx" 
#load "System.Threading.csx" 
#r "../../../packages/System.Buffers/lib/netstandard1.1/System.Buffers.dll" 