#r "System.Runtime.Serialization" 
#r "System.Xml" 
#r "System.Runtime.Serialization" 
#r "System.Xml" 
#r "System.Runtime.Serialization" 
#r "System.Xml" 
#r "../../../packages/FsPickler/lib/net40/FsPickler.dll" 