#load @"Microsoft.CSharp.fsx" 
#load @"NETStandard.Library.fsx" 
#load @"System.ComponentModel.TypeConverter.fsx" 
#load @"System.Runtime.Serialization.Formatters.fsx" 
#load @"System.Runtime.Serialization.Primitives.fsx" 
#load @"System.Xml.XmlDocument.fsx" 
#r "../../../packages/Newtonsoft.Json/lib/portable-net45+win8+wp8+wpa81/Newtonsoft.Json.dll" 