#load @"System.Reflection.fsx" 
#load @"System.Reflection.Extensions.fsx" 
#load @"System.Resources.ResourceManager.fsx" 
#load @"System.Runtime.fsx" 
#load @"System.Runtime.InteropServices.fsx" 
#load @"System.Threading.fsx" 
#r "../../../packages/System.Runtime.InteropServices.RuntimeInformation/lib/netstandard1.1/System.Runtime.InteropServices.RuntimeInformation.dll" 