#load "System.Resources.ResourceManager.csx" 
#load "System.Runtime.csx" 
#r "System.Runtime.Serialization" 
#r "System.Runtime.Serialization" 
#r "mscorlib" 
#r "../../../packages/System.Runtime.Serialization.Primitives/lib/netstandard1.3/System.Runtime.Serialization.Primitives.dll" 