#load @"System.Reflection.fsx" 
#load @"System.Reflection.Emit.ILGeneration.fsx" 
#load @"System.Reflection.Primitives.fsx" 
#load @"System.Runtime.fsx" 
#r "../../../packages/System.Reflection.Emit.Lightweight/lib/netstandard1.3/System.Reflection.Emit.Lightweight.dll" 