#load "System.IO.csx" 
#load "System.Reflection.csx" 
#load "System.Reflection.Emit.ILGeneration.csx" 
#load "System.Reflection.Primitives.csx" 
#load "System.Runtime.csx" 
#r "../../../packages/System.Reflection.Emit/lib/netstandard1.3/System.Reflection.Emit.dll" 