#load "System.Reflection.csx" 
#load "System.Runtime.csx" 
#r "mscorlib" 
#r "mscorlib" 
#r "../../../packages/System.Reflection.TypeExtensions/lib/netstandard1.5/System.Reflection.TypeExtensions.dll" 