#load "System.Collections.csx" 
#load "System.Reflection.csx" 
#load "System.Resources.ResourceManager.csx" 
#load "System.Runtime.csx" 
#load "System.Runtime.Serialization.Primitives.csx" 
#r "mscorlib" 
#r "../../../packages/System.Runtime.Serialization.Formatters/lib/netstandard1.4/System.Runtime.Serialization.Formatters.dll" 